/// ! This file is generated from ../../../codegen/Plug/CPlugVisualIndexedTriangles.xtoml !
/// ! Do not edit this file manually !

class DPlugVisualIndexedTriangles : RawBufferElem {
	DPlugVisualIndexedTriangles(RawBufferElem@ el) {
		if (el.ElSize != SZ_CPlugVisualIndexedTriangles) throw("invalid size for DPlugVisualIndexedTriangles");
		super(el.Ptr, el.ElSize);
	}
	DPlugVisualIndexedTriangles(uint64 ptr) {
		super(ptr, SZ_CPlugVisualIndexedTriangles);
	}

}


