/// ! This file is generated from ../../../codegen/Editor/CGameCtnEditorFree.xtoml !
/// ! Do not edit this file manually !

class DGameCtnEditorFree : RawBufferElem {
	DGameCtnEditorFree(RawBufferElem@ el) {
		if (el.ElSize != 5560) throw("invalid size for DGameCtnEditorFree");
		super(el.Ptr, el.ElSize);
	}
	DGameCtnEditorFree(uint64 ptr) {
		super(ptr, 5560);
	}
	DGameCtnEditorFree(CGameCtnEditorFree@ nod) {
		if (nod is null) throw("not a CGameCtnEditorFree");
		super(Dev_GetPointerForNod(nod), 5560);
	}
	CGameCtnEditorFree@ get_Nod() {
		return cast<CGameCtnEditorFree>(Dev_GetNodFromPointer(ptr));
	}

	// 0x1264 = 0x125C + 0x8
	bool get_IsCalculatingShadows() { return (this.GetBool(O_EDITORFREE_Offset + 0x8)); }
	// 0x1268 = 0x125C + 0xC
	CGameSaveLaunchedCheckpoints@ get_LaunchedCheckpoints() { return cast<CGameSaveLaunchedCheckpoints>(this.GetNod(O_EDITORFREE_Offset + 0xC)); }
}


