/// ! This file is generated from ../../../codegen/Editor/CGameCtnEditorFree.xtoml !
/// ! Do not edit this file manually !

class DGameCtnEditorFree : RawBufferElem {
	DGameCtnEditorFree(RawBufferElem@ el) {
		if (el.ElSize != 5560) throw("invalid size for DGameCtnEditorFree");
		super(el.Ptr, el.ElSize);
	}
	DGameCtnEditorFree(uint64 ptr) {
		super(ptr, 5560);
	}
	DGameCtnEditorFree(CGameCtnEditorFree@ nod) {
		if (nod is null) throw("not a CGameCtnEditorFree");
		super(Dev_GetPointerForNod(nod), 5560);
	}
	CGameCtnEditorFree@ get_Nod() {
		return cast<CGameCtnEditorFree>(Dev_GetNodFromPointer(ptr));
	}

	bool get_IsCalculatingShadows() { return (this.GetBool(0x1264)); }
	CGameSaveLaunchedCheckpoints@ get_LaunchedCheckpoints() { return cast<CGameSaveLaunchedCheckpoints>(this.GetNod(0x1268)); }
}


