/// ! This file is generated from ../../../codegen/Editor/CGameCtnChallenge.xtoml !
/// ! Do not edit this file manually !

class DGameCtnChallenge : RawBufferElem {
	DGameCtnChallenge(RawBufferElem@ el) {
		if (el.ElSize != SZ_CTNCHALLENGE) throw("invalid size for DGameCtnChallenge");
		super(el.Ptr, el.ElSize);
	}
	DGameCtnChallenge(uint64 ptr) {
		super(ptr, SZ_CTNCHALLENGE);
	}
	DGameCtnChallenge(CGameCtnChallenge@ nod) {
		if (nod is null) throw("not a CGameCtnChallenge");
		super(Dev_GetPointerForNod(nod), SZ_CTNCHALLENGE);
	}
	CGameCtnChallenge@ get_Nod() {
		return cast<CGameCtnChallenge>(Dev_GetNodFromPointer(ptr));
	}

	DGameCtnChallenge_Macroblocks@ get_MacroblockInstances() { return DGameCtnChallenge_Macroblocks(this.GetBuffer(O_MAP_MACROBLOCK_INFOS, 0x8, false)); }
	// offset: 0x390 — one CGameCtnZoneGenealogy@ per XZ cell (len = sizeX*sizeZ); see research/MacroblockTerrain.md
	DGameCtnChallenge_TerrainCells@ get_TerrainGenealogies() { return DGameCtnChallenge_TerrainCells(this.GetBuffer(O_MAP_TERRAIN_GENEALOGY_GRID, SZ_CTNZONEGENEALOGY, true)); }
}

class DGameCtnChallenge_Macroblocks : RawBuffer {
	DGameCtnChallenge_Macroblocks(RawBuffer@ buf) {
		super(buf.Ptr, buf.ElSize, buf.StructBehindPtr);
	}
	DGameCtnChallenge_Macroblock@ GetMacroblock(uint i) {
		return DGameCtnChallenge_Macroblock(this[i]);
	}
}


class DGameCtnChallenge_TerrainCells : RawBuffer {
	DGameCtnChallenge_TerrainCells(RawBuffer@ buf) {
		super(buf.Ptr, buf.ElSize, buf.StructBehindPtr);
	}
	DGameCtnChallenge_TerrainCell@ GetTerrainCell(uint i) {
		return DGameCtnChallenge_TerrainCell(this[i]);
	}
}

// unk = uint64, 0x4d0
// unk = uint64, 0x368
class DGameCtnChallenge_TerrainCell : RawBufferElem {
	DGameCtnChallenge_TerrainCell(RawBufferElem@ el) {
		if (el.ElSize != SZ_CTNZONEGENEALOGY) throw("invalid size for DGameCtnChallenge_TerrainCell");
		super(el.Ptr, el.ElSize);
	}
	DGameCtnChallenge_TerrainCell(uint64 ptr) {
		super(ptr, SZ_CTNZONEGENEALOGY);
	}
	DGameCtnChallenge_TerrainCell(CGameCtnZoneGenealogy@ nod) {
		if (nod is null) throw("not a CGameCtnZoneGenealogy");
		super(Dev_GetPointerForNod(nod), SZ_CTNZONEGENEALOGY);
	}
	CGameCtnZoneGenealogy@ get_Nod() {
		return cast<CGameCtnZoneGenealogy>(Dev_GetNodFromPointer(ptr));
	}

	DGameCtnZoneGenealogy@ AsGenealogyStruct() { return DGameCtnZoneGenealogy(this.Ptr); }
}


class DGameCtnChallenge_Macroblock : RawBufferElem {
	DGameCtnChallenge_Macroblock(RawBufferElem@ el) {
		if (el.ElSize != 0x8) throw("invalid size for DGameCtnChallenge_Macroblock");
		super(el.Ptr, el.ElSize);
	}
	DGameCtnChallenge_Macroblock(uint64 ptr) {
		super(ptr, 0x8);
	}

	int get_InstId() { return (this.GetInt32(0x0)); }
	void set_InstId(int value) { this.SetInt32(0x0, value); }
	string get_MbName() { return (this.GetMwIdValue(0x4)); }
	void set_MbName(const string &in value) { this.SetMwIdValue(0x4, value); }
	uint get_MbMwId() { return (this.GetUint32(0x4)); }
	void set_MbMwId(uint value) { this.SetUint32(0x4, value); }
}


