/// ! This file is generated from ../../../codegen/Editor/CursorBlock.xtoml !
/// ! Do not edit this file manually !

class DGameCursorBlock : RawBufferElem {
	DGameCursorBlock(RawBufferElem@ el) {
		if (el.ElSize != SZ_CGAMECURSORBLOCK) throw("invalid size for DGameCursorBlock");
		super(el.Ptr, el.ElSize);
	}
	DGameCursorBlock(uint64 ptr) {
		super(ptr, SZ_CGAMECURSORBLOCK);
	}
	DGameCursorBlock(CGameCursorBlock@ nod) {
		if (nod is null) throw("not a CGameCursorBlock");
		super(Dev_GetPointerForNod(nod), SZ_CGAMECURSORBLOCK);
	}
	CGameCursorBlock@ get_Nod() {
		return cast<CGameCursorBlock>(Dev_GetNodFromPointer(ptr));
	}

}


