/// ! This file is generated from ../../../codegen/Game/CGameCtnMediaClipPlayer.xtoml !
/// ! Do not edit this file manually !

// can find via: game scene: 1c0, 100, 90
class DGameCtnMediaClipPlayer : RawBufferElem {
	DGameCtnMediaClipPlayer(RawBufferElem@ el) {
		if (el.ElSize != 0x338) throw("invalid size for DGameCtnMediaClipPlayer");
		super(el.Ptr, el.ElSize);
	}
	DGameCtnMediaClipPlayer(uint64 ptr) {
		super(ptr, 0x338);
	}

	// When false, values are still updated but no light trails are drawn
	bool get_ShouldDrawLightTrails() { return (this.GetBool(0x2B8)); }
	void set_ShouldDrawLightTrails(bool value) { this.SetBool(0x2B8, value); }
	// when LightTrails are active, offsets 0x2F8 through 0x330 are used
	bool get_LightTrails() { return (this.GetBool(0x30C)); }
	void set_LightTrails(bool value) { this.SetBool(0x30C, value); }
	float get_SecondsFrameTime() { return (this.GetFloat(0x2F8)); }
	void set_SecondsFrameTime(float value) { this.SetFloat(0x2F8, value); }
	float get_SecondsFloat() { return (this.GetFloat(0x2FC)); }
	void set_SecondsFloat(float value) { this.SetFloat(0x2FC, value); }
	// value: 1.0
	float get_Unk300() { return (this.GetFloat(0x300)); }
	void set_Unk300(float value) { this.SetFloat(0x300, value); }
	float get_SecondsFrameTime2() { return (this.GetFloat(0x304)); }
	void set_SecondsFrameTime2(float value) { this.SetFloat(0x304, value); }
	// unk, value: 1478695
	uint get_Unk308() { return (this.GetUint32(0x308)); }
	void set_Unk308(uint value) { this.SetUint32(0x308, value); }
	uint64 get_Ptr310() { return (this.GetUint64(0x310)); }
	void set_Ptr310(uint64 value) { this.SetUint64(0x310, value); }
	uint64 get_FuncPtr318() { return (this.GetUint64(0x318)); }
	void set_FuncPtr318(uint64 value) { this.SetUint64(0x318, value); }
	// 0x7FF7FFFF
	uint get_Unk320() { return (this.GetUint32(0x320)); }
	void set_Unk320(uint value) { this.SetUint32(0x320, value); }
	// value: 1.0
	float get_Unk324() { return (this.GetFloat(0x324)); }
	void set_Unk324(float value) { this.SetFloat(0x324, value); }
	float get_SecondsFloat2() { return (this.GetFloat(0x328)); }
	void set_SecondsFloat2(float value) { this.SetFloat(0x328, value); }
	float get_SecondsFrameTime3() { return (this.GetFloat(0x32C)); }
	void set_SecondsFrameTime3(float value) { this.SetFloat(0x32C, value); }
}


