/// ! This file is generated from ../../../../codegen/Editor/LightMap/LightMapStructs.xtoml !
/// ! Do not edit this file manually !

// from _SPimp, at 0x100 there is an embedded CHmsLightMapParam node
// SZ_NHmsLightMap_SPImp = 0x4E0;
class D_NHmsLightMap_SPImp : RawBufferElem {
	D_NHmsLightMap_SPImp(RawBufferElem@ el) {
		if (el.ElSize != 0x4E0) throw("invalid size for D_NHmsLightMap_SPImp");
		super(el.Ptr, el.ElSize);
	}
	D_NHmsLightMap_SPImp(uint64 ptr) {
		super(ptr, 0x4E0);
	}

	// CacheSize + 0x80
	DHmsLightMapParam@ get_LightMapParams() { return DHmsLightMapParam(this.Ptr + 0x100); }
}


// SZ_CHmsLightMapParam = 0x128;
class DHmsLightMapParam : RawBufferElem {
	DHmsLightMapParam(RawBufferElem@ el) {
		if (el.ElSize != 0x128) throw("invalid size for DHmsLightMapParam");
		super(el.Ptr, el.ElSize);
	}
	DHmsLightMapParam(uint64 ptr) {
		super(ptr, 0x128);
	}
	DHmsLightMapParam(CHmsLightMapParam@ nod) {
		if (nod is null) throw("not a CHmsLightMapParam");
		super(Dev_GetPointerForNod(nod), 0x128);
	}
	CHmsLightMapParam@ get_Nod() {
		return cast<CHmsLightMapParam>(Dev_GetNodFromPointer(ptr));
	}

	uint get_AmbSamples() { return (this.GetUint32(0xA8)); }
	void set_AmbSamples(uint value) { this.SetUint32(0xA8, value); }
	uint get_DirSamples() { return (this.GetUint32(0xAC)); }
	void set_DirSamples(uint value) { this.SetUint32(0xAC, value); }
	uint get_PntSamples() { return (this.GetUint32(0xB0)); }
	void set_PntSamples(uint value) { this.SetUint32(0xB0, value); }
	uint get_DepthPeelGroupMaxPerAxe() { return (this.GetUint32(0xB4)); }
	void set_DepthPeelGroupMaxPerAxe(uint value) { this.SetUint32(0xB4, value); }
	// values that are 4 by default
	uint get_unk1_default4() { return (this.GetUint32(0x30)); }
	void set_unk1_default4(uint value) { this.SetUint32(0x30, value); }
	uint get_unk2_default4() { return (this.GetUint32(0x34)); }
	void set_unk2_default4(uint value) { this.SetUint32(0x34, value); }
	// values that are 3 which might correspond to m_CompressMode, m_Qualit, m_Bump
	uint get_unk1_default3() { return (this.GetUint32(0xBC)); }
	void set_unk1_default3(uint value) { this.SetUint32(0xBC, value); }
	uint get_unk2_default3() { return (this.GetUint32(0XE4)); }
	void set_unk2_default3(uint value) { this.SetUint32(0XE4, value); }
	// values that are 1 by default
	uint get_unk1_default1() { return (this.GetUint32(0x18)); }
	void set_unk1_default1(uint value) { this.SetUint32(0x18, value); }
	uint get_unk2_default1() { return (this.GetUint32(0x28)); }
	void set_unk2_default1(uint value) { this.SetUint32(0x28, value); }
	uint get_unk3_default1() { return (this.GetUint32(0x3C)); }
	void set_unk3_default1(uint value) { this.SetUint32(0x3C, value); }
	uint get_unk4_default1() { return (this.GetUint32(0x4C)); }
	void set_unk4_default1(uint value) { this.SetUint32(0x4C, value); }
	uint get_unk5_default1() { return (this.GetUint32(0x64)); }
	void set_unk5_default1(uint value) { this.SetUint32(0x64, value); }
	uint get_unk6_default1() { return (this.GetUint32(0x7C)); }
	void set_unk6_default1(uint value) { this.SetUint32(0x7C, value); }
	uint get_unk7_default1() { return (this.GetUint32(0x84)); }
	void set_unk7_default1(uint value) { this.SetUint32(0x84, value); }
	uint get_unk8_default1() { return (this.GetUint32(0x94)); }
	void set_unk8_default1(uint value) { this.SetUint32(0x94, value); }
	uint get_unk9_default1() { return (this.GetUint32(0xC0)); }
	void set_unk9_default1(uint value) { this.SetUint32(0xC0, value); }
	uint get_unk10_default1() { return (this.GetUint32(0xC4)); }
	void set_unk10_default1(uint value) { this.SetUint32(0xC4, value); }
	uint get_unk11_default1() { return (this.GetUint32(0xCC)); }
	void set_unk11_default1(uint value) { this.SetUint32(0xCC, value); }
	uint get_unk12_default1() { return (this.GetUint32(0xD0)); }
	void set_unk12_default1(uint value) { this.SetUint32(0xD0, value); }
	uint get_unk13_default1() { return (this.GetUint32(0xDC)); }
	void set_unk13_default1(uint value) { this.SetUint32(0xDC, value); }
	uint get_unk14_default1() { return (this.GetUint32(0xE0)); }
	void set_unk14_default1(uint value) { this.SetUint32(0xE0, value); }
	uint get_unk15_default1() { return (this.GetUint32(0xEC)); }
	void set_unk15_default1(uint value) { this.SetUint32(0xEC, value); }
	uint get_unk16_default1() { return (this.GetUint32(0xF4)); }
	void set_unk16_default1(uint value) { this.SetUint32(0xF4, value); }
	uint get_unk17_default1() { return (this.GetUint32(0xF8)); }
	void set_unk17_default1(uint value) { this.SetUint32(0xF8, value); }
	uint get_unk18_default1() { return (this.GetUint32(0xFC)); }
	void set_unk18_default1(uint value) { this.SetUint32(0xFC, value); }
	uint get_unk19_default1() { return (this.GetUint32(0xFC)); }
	void set_unk19_default1(uint value) { this.SetUint32(0xFC, value); }
	uint get_unk20_default1() { return (this.GetUint32(0x110)); }
	void set_unk20_default1(uint value) { this.SetUint32(0x110, value); }
	uint get_unk21_default1() { return (this.GetUint32(0x114)); }
	void set_unk21_default1(uint value) { this.SetUint32(0x114, value); }
}


