/// ! This file is generated from ../../../codegen/System/CSystemFid.xtoml !
/// ! Do not edit this file manually !

class DSystemFidFile : RawBufferElem {
	DSystemFidFile(RawBufferElem@ el) {
		if (el.ElSize != SZ_FID_FILE) throw("invalid size for DSystemFidFile");
		super(el.Ptr, el.ElSize);
	}
	DSystemFidFile(uint64 ptr) {
		super(ptr, SZ_FID_FILE);
	}
	DSystemFidFile(CSystemFidFile@ nod) {
		if (nod is null) throw("not a CSystemFidFile");
		super(Dev_GetPointerForNod(nod), SZ_FID_FILE);
	}
	CSystemFidFile@ get_Nod() {
		return cast<CSystemFidFile>(Dev_GetNodFromPointer(ptr));
	}

	CSystemFidsFolder@ get_ParentFolder() { return cast<CSystemFidsFolder>(this.GetNod(0x18)); }
	uint get_NodClassId() { return (this.GetUint32(O_FID_NodClassId)); }
	CMwNod@ get_FidNod() { return cast<CMwNod>(this.GetNod(O_FID_Nod)); }
	void set_FidNod(CMwNod@ value) { this.SetNod(O_FID_Nod, value); }
	uint get_ByteSize() { return (this.GetUint32(O_FID_ByteSize)); }
}


