/// ! This file is generated from ../../../codegen/System/CSystemPackDesc.xtoml !
/// ! Do not edit this file manually !

class DSystemPackDesc : RawBufferElem {
	DSystemPackDesc(RawBufferElem@ el) {
		if (el.ElSize != SZ_PACKDESC) throw("invalid size for DSystemPackDesc");
		super(el.Ptr, el.ElSize);
	}
	DSystemPackDesc(uint64 ptr) {
		super(ptr, SZ_PACKDESC);
	}
	DSystemPackDesc(CSystemPackDesc@ nod) {
		if (nod is null) throw("not a CSystemPackDesc");
		super(Dev_GetPointerForNod(nod), SZ_PACKDESC);
	}
	CSystemPackDesc@ get_Nod() {
		return cast<CSystemPackDesc>(Dev_GetNodFromPointer(ptr));
	}

	string get_Name() { return (this.GetString(0x20)); }
	void set_Name(const string &in value) { this.SetString(0x20, value); }
	string get_Url() { return (this.GetString(0x30)); }
	void set_Url(const string &in value) { this.SetString(0x30, value); }
	CSystemFidFile@ get_Fid() { return cast<CSystemFidFile>(this.GetNod(0x60)); }
	void set_Fid(CSystemFidFile@ value) { this.SetNod(0x60, value); }
}


